sudo: required

dist: trusty
arch: ppc64le

branches:
  except:
  - stable

language: cpp

env:
  - BAZEL_VERSION=0.4.5

cache:
  directories:
    - $HOME/bazel/install
    - $HOME/bazel/outbase
    - $HOME/clang

before_install:
    - mkdir -p ${HOME}/bazel/install
    - cd ${HOME}/bazel/install
    - sudo apt-get update -y 
    - sudo apt-get install -y openjdk-8-jdk
    - sudo apt-get install -y wget
    - sudo apt-get install -y curl
    - sudo apt-get install -y unzip
    - sudo apt-get install -y zip
    - sudo apt-get install -y git
    - sudo apt-get install -y rsync
    - sudo apt-get install -y g++
    - sudo apt-get install -y curl
    - sudo apt-get install -y patch
    - sudo apt-get install -y python-pip
    - curl -fSsL -O https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-dist.zip
    - unzip bazel-0.4.5-dist.zip
    - sudo apt-get install -y python3
    - alias python=python3
    - sed -i '/--action_env=PATH \\/a\  --host_javabase=@bazel_tools//tools/jdk:jdk \\' compile.sh
    - bash ./compile.sh
    - sudo apt-get -f install -qqy uuid-dev
    - cd ${TRAVIS_BUILD_DIR}
    - mv tools/bazel.rc tools/bazel.rc.orig
    - cat tools/bazel.rc.travis tools/bazel.rc.orig > tools/bazel.rc
    

script:
  - script/check-style
  - CC=/usr/bin/gcc-4.9 CXX=/usr/bin/g++-4.9 bazel --output_base=${HOME}/bazel/outbase test //...

notifications:
  slack: istio-dev:wEEEbaabdP5ieCgDOFetA9nX
