sudo: required

dist: trusty

branches:
  except:
  - stable

language: cpp

env:
  - BAZEL_VERSION=3.0.0

cache:
  directories:
    - $HOME/bazel/install
    - $HOME/bazel/outbase
    - $HOME/clang

before_install:
    - apt-get update -y 
    - apt-get install -y --no-install-recommends \
    - openjdk-8-jdk \
    - wget \
    - curl \
    - unzip \
    - zip \
    - git \
    - rsync \
    - g++ \
    - curl \
    - patch \
    - python-pip
    - mkdir bazel && cd bazel
    - curl -fSsL -O https://github.com/bazelbuild/bazel/releases/download/3.0.0/bazel-3.0.0-dist.zip
    - unzip bazel-3.0.0-dist.zip

    - apt-get install python3
    - alias python=python3
    - sed -i '/--action_env=PATH \\/a\  --host_javabase=@bazel_tools//tools/jdk:jdk \\' compile.sh
    - bash ./compile.sh

script:
  - script/check-style
  - CC=/usr/bin/gcc-4.9 CXX=/usr/bin/g++-4.9 bazel --output_base=${HOME}/bazel/outbase test //...

notifications:
  slack: istio-dev:wEEEbaabdP5ieCgDOFetA9nX
