sudo: required

dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/ppa
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
