sudo: required

dist: trusty
arch: ppc64le

before_install:
   - sudo apt-get update
   - sudo apt-get install software-properties-common
   - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
   - sudo apt-get update
   - sudo apt-get install gcc-4.9 g++-4.9
   - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

language: cpp

jdk:
  - oraclejdk8

env:
  - BAZEL_VERSION=0.4.5
  
script:
  - gcc -v
