sudo: required

arch: ppc64le
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - software-properties-common
    - gcc-4.9

env:
  - BAZEL_VERSION=0.4.5
script:
  - gcc -v

