sudo: required

arch: ppc64le
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9
  
env:
  - BAZEL_VERSION=0.4.5
script:
  - gcc -v

    
